- hosts: all
  tasks:
  - name: sync host file
    copy: src=/etc/hosts dest=/etc/hosts backup=yes
  - name: mkdir
    file: dest={{item.dest}} state=directory
    with_items:
       - dest: /scripts
       - dest: /backup
       - dest: /application
